# Generated by Django 5.2.5 on 2025-09-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerclient',
            old_name='subscription_active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='partner',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='partnerclient',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PartnerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscription_plan', models.CharField(max_length=20)),
                ('payment_date', models.DateTimeField()),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='partners.partnerclient')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='partners.partner')),
            ],
            options={
                'indexes': [models.Index(fields=['payment_date', 'status'], name='partners_pa_payment_b38fe6_idx')],
            },
        ),
    ]
