# Generated by Django 5.2.5 on 2025-11-08 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_rename_subscription_active_partnerclient_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('gateway_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_status', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payoutrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='partner',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='partner',
            name='total_paid_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='mailing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('PAYPAL', 'PayPal'), ('WISE', 'Wise'), ('CHECK', 'Check')], default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='receipt_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='swift_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='wise_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved - Processing'), ('PAID', 'Paid Successfully'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by Partner')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status', 'created_at'], name='partners_pa_status_3b7729_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['partner', 'created_at'], name='partners_pa_partner_5734b5_idx'),
        ),
        migrations.AddField(
            model_name='payouttransaction',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_transactions', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='payouttransaction',
            name='payout_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='partners.payoutrequest'),
        ),
    ]
