# Generated by Django 5.2.5 on 2025-11-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_payouttransaction_alter_payoutrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercommission',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='partnercommission',
            unique_together={('stripe_invoice_id', 'client')},
        ),
        migrations.AddIndex(
            model_name='partnercommission',
            index=models.Index(fields=['stripe_invoice_id'], name='partners_pa_stripe__baef98_idx'),
        ),
    ]
