# Generated by Django 5.2.5 on 2025-08-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code_used',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
