# Generated by Django 5.2.5 on 2025-09-02 13:42

import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_userprofile_referred_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=invoices.models.company_pdf_upload_path),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='xml_file',
            field=models.FileField(blank=True, null=True, upload_to=invoices.models.company_xml_upload_path),
        ),
    ]
