# Generated by Django 5.2.5 on 2025-09-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_pdf_file_alter_invoice_xml_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='Dubai', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='emirate',
            field=models.CharField(choices=[('ABU_DHABI', 'Abu Dhabi'), ('DUBAI', 'Dubai'), ('SHARJAH', 'Sharjah'), ('AJMAN', 'Ajman'), ('UMM_AL_QAIWAIN', 'Umm Al Qaiwain'), ('RAS_AL_KHAIMAH', 'Ras Al Khaimah'), ('FUJAIRAH', 'Fujairah')], default='DUBAI', max_length=20),
        ),
    ]
