# Generated by Django 5.2.5 on 2025-09-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_company_city_company_emirate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
    ]
