# Generated by Django 5.2.5 on 2025-09-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_company_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='emirate',
        ),
    ]
