# Generated by Django 5.2.5 on 2025-09-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_remove_company_emirate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='emirate',
            field=models.CharField(choices=[('ABU_DHABI', 'Abu Dhabi'), ('DUBAI', 'Dubai'), ('SHARJAH', 'Sharjah'), ('AJMAN', 'Ajman'), ('UMM_AL_QAIWAIN', 'Umm Al Qaiwain'), ('RAS_AL_KHAIMAH', 'Ras Al Khaimah'), ('FUJAIRAH', 'Fujairah')], default='DUBAI', max_length=20),
        ),
    ]
