# Generated by Django 5.2.5 on 2025-10-19 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_company_emirate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_details',
            field=models.JSONField(blank=True, help_text='Custom bank details for this invoice', null=True),
        ),
        migrations.CreateModel(
            name='CompanyBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Emirates NBD', max_length=255)),
                ('account_number', models.CharField(default='1234 5678 9012', max_length=50)),
                ('iban', models.CharField(default='AE00 1234 5678 9012', max_length=50)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='invoices.company')),
            ],
            options={
                'verbose_name_plural': 'Company Bank Details',
            },
        ),
    ]
